name: Build and Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create dummy .env file
        working-directory: ./smart_campus_navigation_system
        env:
          SUPABASE_URL: "${{ secrets.SUPABASE_URL }}"
          SUPABASE_ANON_KEY: "${{ secrets.SUPABASE_ANON_KEY }}"
          MAPTILER_API_KEY: "${{ secrets.MAPTILER_API_KEY }}"
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "MAPTILER_API_KEY=$MAPTILER_API_KEY" >> .env

      - name: Get dependencies
        working-directory: ./smart_campus_navigation_system
        run: flutter pub get

      - name: Build APK
        working-directory: ./smart_campus_navigation_system
        # We append the GitHub run number as the build number so the app knows when there's an update
        run: flutter build apk --release --build-number=${{ github.run_number }}

      - name: Extract version from pubspec.yaml
        id: extract_version
        working-directory: ./smart_campus_navigation_system
        run: |
          version=$(grep '^version: ' pubspec.yaml | tr -d '\r' | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.extract_version.outputs.VERSION }}+${{ github.run_number }}
          name: Release v${{ steps.extract_version.outputs.VERSION }} (Build ${{ github.run_number }})
          draft: false
          prerelease: false
          files: smart_campus_navigation_system/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
